/**
 * 작업지시 Mock 데이터
 */
import type { WorkOrderDTO } from '@/api/generated/models';

/**
 * Mock 작업지시 데이터
 */
export const mockWorkOrders: WorkOrderDTO[] = [
  {
    id: 1,
    name: '공조기 정기점검',
    state: 'PROCESSING',
    stateName: '처리중',
    firstClassName: '설비관리',
    secondClassName: '공조설비',
    buildingName: 'A동',
    planStartDate: '2026-02-08',
    planEndDate: '2026-02-10',
    writeDate: '2026-02-07 09:00:00',
    writerName: '홍길동',
    itemSize: 5,
  },
  {
    id: 2,
    name: '엘리베이터 안전점검',
    state: 'ISSUE',
    stateName: '발행',
    firstClassName: '설비관리',
    secondClassName: '승강설비',
    buildingName: 'B동',
    planStartDate: '2026-02-09',
    planEndDate: '2026-02-11',
    writeDate: '2026-02-08 10:30:00',
    writerName: '이영희',
    // assigneeName: '박민수',
    itemSize: 3,
  },
  {
    id: 3,
    name: '소방설비 정기점검',
    state: 'REQ_COMPLETE',
    stateName: '완료요청',
    firstClassName: '안전관리',
    secondClassName: '소방설비',
    buildingName: 'C동',
    planStartDate: '2026-02-06',
    planEndDate: '2026-02-08',
    writeDate: '2026-02-05 14:00:00',
    writerName: '최지훈',
    // assigneeName: '정수진',
    itemSize: 8,
  },
  {
    id: 4,
    name: '전기설비 월간점검',
    state: 'WRITE',
    stateName: '작성',
    firstClassName: '설비관리',
    secondClassName: '전기설비',
    buildingName: 'A동',
    planStartDate: '2026-02-10',
    planEndDate: '2026-02-12',
    writeDate: '2026-02-08 11:00:00',
    writerName: '김민준',
    itemSize: 6,
  },
  {
    id: 5,
    name: '급배수 설비점검',
    state: 'COMPLETE',
    stateName: '완료',
    firstClassName: '설비관리',
    secondClassName: '급배수설비',
    buildingName: 'B동',
    planStartDate: '2026-02-04',
    planEndDate: '2026-02-06',
    writeDate: '2026-02-03 09:30:00',
    writerName: '이서연',
    // assigneeName: '박준호',
    itemSize: 4,
  },
  {
    id: 6,
    name: '냉난방기 필터 교체',
    state: 'PROCESSING',
    stateName: '처리중',
    firstClassName: '설비관리',
    secondClassName: '공조설비',
    buildingName: 'C동',
    planStartDate: '2026-02-08',
    planEndDate: '2026-02-09',
    writeDate: '2026-02-07 15:20:00',
    writerName: '윤지혜',
    // assigneeName: '강동현',
    itemSize: 2,
  },
  {
    id: 7,
    name: '보일러 정기점검',
    state: 'CANCEL',
    stateName: '취소',
    firstClassName: '설비관리',
    secondClassName: '난방설비',
    buildingName: 'A동',
    planStartDate: '2026-02-07',
    planEndDate: '2026-02-08',
    writeDate: '2026-02-06 13:00:00',
    writerName: '최민수',
    itemSize: 3,
  },
  {
    id: 8,
    name: 'CCTV 정기점검',
    state: 'ISSUE',
    stateName: '발행',
    firstClassName: '안전관리',
    secondClassName: '방범설비',
    buildingName: 'B동',
    planStartDate: '2026-02-09',
    planEndDate: '2026-02-10',
    writeDate: '2026-02-08 16:45:00',
    writerName: '송하윤',
    // assigneeName: '임서준',
    itemSize: 10,
  },
  {
    id: 9,
    name: '주차장 조명 점검',
    state: 'PROCESSING',
    stateName: '처리중',
    firstClassName: '시설관리',
    secondClassName: '조명설비',
    buildingName: '지하주차장',
    planStartDate: '2026-02-08',
    planEndDate: '2026-02-09',
    writeDate: '2026-02-07 10:00:00',
    writerName: '한지우',
    // assigneeName: '조은서',
    itemSize: 7,
  },
  {
    id: 10,
    name: '옥상 방수 점검',
    state: 'REQ_COMPLETE',
    stateName: '완료요청',
    firstClassName: '시설관리',
    secondClassName: '건축물관리',
    buildingName: 'C동',
    planStartDate: '2026-02-06',
    planEndDate: '2026-02-08',
    writeDate: '2026-02-05 11:30:00',
    writerName: '권도윤',
    // assigneeName: '신예은',
    itemSize: 1,
  },
];
