/**
 * 승인/확인 Mock 데이터
 */
import type { ApprovalItemDTO } from '../types';

/**
 * Mock 승인 항목 목록
 */
export const mockApprovalItems: ApprovalItemDTO[] = [
  // 오늘 할 일
  {
    id: 1,
    type: 'WORK',
    typeName: '작업지시',
    title: '[긴급] 1층 로비 누수 수리',
    writerName: '김현장',
    buildingName: 'A동',
    createdDate: '2026-02-10',
    completedDate: '2026-02-10',
    status: 'PENDING',
    priority: 'HIGH',
    attachmentCount: 3,
    progress: 100,
  },
  {
    id: 2,
    type: 'PATROL',
    typeName: '순찰',
    title: '2월 정기 순찰 (2층)',
    writerName: '이순찰',
    buildingName: 'B동',
    createdDate: '2026-02-10',
    completedDate: '2026-02-10',
    status: 'PENDING',
    priority: 'MEDIUM',
    progress: 85,
  },
  {
    id: 3,
    type: 'EMERGENCY',
    typeName: '긴급',
    title: '3층 화재 경보기 오작동',
    writerName: '박긴급',
    buildingName: 'C동',
    createdDate: '2026-02-10',
    completedDate: '2026-02-10',
    status: 'PENDING',
    priority: 'HIGH',
    attachmentCount: 1,
  },
  {
    id: 4,
    type: 'REGULAR',
    typeName: '정기',
    title: '2월 정기점검 - 전기설비',
    writerName: '최전기',
    buildingName: 'A동',
    createdDate: '2026-02-10',
    completedDate: '2026-02-10',
    status: 'APPROVED',
    priority: 'MEDIUM',
  },
  // 과거 미확인
  {
    id: 5,
    type: 'ADHOC',
    typeName: '수시',
    title: '지하 주차장 조명 교체',
    writerName: '정수시',
    buildingName: 'B동',
    createdDate: '2026-02-09',
    completedDate: '2026-02-09',
    status: 'PENDING',
    priority: 'LOW',
    attachmentCount: 2,
  },
  {
    id: 6,
    type: 'DAILY',
    typeName: '일상',
    title: '로비 청소 점검',
    writerName: '강일상',
    buildingName: 'A동',
    createdDate: '2026-02-08',
    completedDate: '2026-02-08',
    status: 'PENDING',
    priority: 'LOW',
  },
  {
    id: 7,
    type: 'WORK',
    typeName: '작업지시',
    title: '옥상 방수 작업',
    writerName: '홍작업',
    buildingName: 'C동',
    createdDate: '2026-02-07',
    completedDate: '2026-02-07',
    status: 'PENDING',
    priority: 'MEDIUM',
    progress: 100,
  },
  {
    id: 8,
    type: 'PATROL',
    typeName: '순찰',
    title: '2월 1차 순찰 (전체)',
    writerName: '이순찰',
    buildingName: '전체',
    createdDate: '2026-02-05',
    completedDate: '2026-02-05',
    status: 'APPROVED',
    priority: 'MEDIUM',
  },
  {
    id: 9,
    type: 'WORK',
    typeName: '작업지시',
    title: '공조기 필터 교체',
    writerName: '김공조',
    buildingName: 'A동',
    createdDate: '2026-02-04',
    completedDate: '2026-02-04',
    status: 'PENDING',
    priority: 'MEDIUM',
    attachmentCount: 1,
  },
  {
    id: 10,
    type: 'EMERGENCY',
    typeName: '긴급',
    title: '엘리베이터 고장',
    writerName: '박엘리',
    buildingName: 'B동',
    createdDate: '2026-02-03',
    completedDate: '2026-02-03',
    status: 'APPROVED',
    priority: 'HIGH',
  },
];
