/**
 * 설비 Mock 데이터
 */
import type { FacilityDTO, FacilityClassification } from '../types';

/**
 * Mock 설비 분류 데이터
 */
export const mockFacilityClassifications: FacilityClassification[] = [
  // 1차 분류
  { id: 1, name: '공조설비', level: 1 },
  { id: 2, name: '전기설비', level: 1 },
  { id: 3, name: '소방설비', level: 1 },
  { id: 4, name: '위생설비', level: 1 },

  // 2차 분류 (공조설비)
  { id: 11, name: '냉난방기', parentId: 1, level: 2 },
  { id: 12, name: '환기시설', parentId: 1, level: 2 },
  { id: 13, name: '공기조화기', parentId: 1, level: 2 },

  // 2차 분류 (전기설비)
  { id: 21, name: '변압기', parentId: 2, level: 2 },
  { id: 22, name: '배전반', parentId: 2, level: 2 },
  { id: 23, name: '발전기', parentId: 2, level: 2 },

  // 2차 분류 (소방설비)
  { id: 31, name: '소화설비', parentId: 3, level: 2 },
  { id: 32, name: '경보설비', parentId: 3, level: 2 },

  // 3차 분류 (냉난방기)
  { id: 111, name: '에어컨', parentId: 11, level: 3 },
  { id: 112, name: '보일러', parentId: 11, level: 3 },
];

/**
 * Mock 설비 목록 데이터
 */
export const mockFacilities: FacilityDTO[] = [
  {
    id: 1,
    name: 'A동 중앙 냉방기 #1',
    code: 'HVAC-A-001',
    type: '중앙 공조기',
    buildingName: 'A동',
    floor: '지하 1층',
    location: '기계실',
    manufacturer: 'LG전자',
    model: 'AHU-500',
    capacity: '500RT',
    installDate: '2020-03-15',
    lastCheckDate: '2024-02-01',
    status: 'NORMAL',
    managerName: '김철수',
    managerPhone: '010-1234-5678',
    description: 'A동 전체를 담당하는 중앙 냉방기입니다.',
    firstCategoryId: 1,
    firstClassName: '공조설비',
    secondCategoryId: 11,
    secondClassName: '냉난방기',
    thirdCategoryId: 111,
    thirdClassName: '에어컨',
    imageUrl: 'https://picsum.photos/400/300?random=1',
    specifications: [
      { name: '냉방 용량', value: '500', unit: 'RT' },
      { name: '전압', value: '380', unit: 'V' },
      { name: '소비 전력', value: '150', unit: 'kW' },
      { name: '냉매', value: 'R-410A', unit: '' },
    ],
    workOrderCount: 12,
  },
  {
    id: 2,
    name: 'B동 변압기 #2',
    code: 'ELEC-B-002',
    type: '몰드 변압기',
    buildingName: 'B동',
    floor: '지하 2층',
    location: '전기실',
    manufacturer: '효성중공업',
    model: 'TR-1000',
    capacity: '1000kVA',
    installDate: '2019-11-20',
    lastCheckDate: '2024-01-28',
    status: 'WARNING',
    managerName: '이영희',
    managerPhone: '010-2345-6789',
    description: 'B동 전력 공급을 담당하는 변압기입니다. 정기 점검 필요.',
    firstCategoryId: 2,
    firstClassName: '전기설비',
    secondCategoryId: 21,
    secondClassName: '변압기',
    imageUrl: 'https://picsum.photos/400/300?random=2',
    specifications: [
      { name: '용량', value: '1000', unit: 'kVA' },
      { name: '1차 전압', value: '22900', unit: 'V' },
      { name: '2차 전압', value: '380', unit: 'V' },
      { name: '냉각 방식', value: '자냉식', unit: '' },
    ],
    workOrderCount: 8,
  },
  {
    id: 3,
    name: 'C동 스프링클러 펌프',
    code: 'FIRE-C-003',
    type: '소화펌프',
    buildingName: 'C동',
    floor: '지하 1층',
    location: '펌프실',
    manufacturer: '한국펌프',
    model: 'SP-2000',
    capacity: '2000LPM',
    installDate: '2021-05-10',
    lastCheckDate: '2024-02-05',
    status: 'NORMAL',
    managerName: '박민수',
    managerPhone: '010-3456-7890',
    description: 'C동 스프링클러 소화설비 펌프입니다.',
    firstCategoryId: 3,
    firstClassName: '소방설비',
    secondCategoryId: 31,
    secondClassName: '소화설비',
    imageUrl: 'https://picsum.photos/400/300?random=3',
    specifications: [
      { name: '양정', value: '100', unit: 'm' },
      { name: '유량', value: '2000', unit: 'LPM' },
      { name: '전동기 출력', value: '75', unit: 'kW' },
      { name: '압력', value: '10', unit: 'kgf/cm²' },
    ],
    workOrderCount: 5,
  },
  {
    id: 4,
    name: 'A동 환기팬 #3',
    code: 'HVAC-A-004',
    type: '배기팬',
    buildingName: 'A동',
    floor: '옥상',
    location: '기계실',
    manufacturer: '삼성전자',
    model: 'VF-300',
    capacity: '30000CMH',
    installDate: '2020-08-25',
    lastCheckDate: '2024-01-15',
    status: 'MAINTENANCE',
    managerName: '김철수',
    managerPhone: '010-1234-5678',
    description: 'A동 환기 시스템 배기팬입니다. 현재 점검 중.',
    firstCategoryId: 1,
    firstClassName: '공조설비',
    secondCategoryId: 12,
    secondClassName: '환기시설',
    imageUrl: 'https://picsum.photos/400/300?random=4',
    specifications: [
      { name: '풍량', value: '30000', unit: 'CMH' },
      { name: '정압', value: '250', unit: 'Pa' },
      { name: '전동기 출력', value: '15', unit: 'kW' },
    ],
    workOrderCount: 15,
  },
  {
    id: 5,
    name: 'B동 비상발전기',
    code: 'ELEC-B-005',
    type: '디젤발전기',
    buildingName: 'B동',
    floor: '지하 2층',
    location: '발전기실',
    manufacturer: '대우중공업',
    model: 'DG-500',
    capacity: '500kW',
    installDate: '2019-03-01',
    lastCheckDate: '2024-01-20',
    status: 'ERROR',
    managerName: '이영희',
    managerPhone: '010-2345-6789',
    description: 'B동 비상 전원 공급 발전기입니다. 시동 불량 상태.',
    firstCategoryId: 2,
    firstClassName: '전기설비',
    secondCategoryId: 23,
    secondClassName: '발전기',
    imageUrl: 'https://picsum.photos/400/300?random=5',
    specifications: [
      { name: '정격 출력', value: '500', unit: 'kW' },
      { name: '전압', value: '380', unit: 'V' },
      { name: '주파수', value: '60', unit: 'Hz' },
      { name: '연료', value: '경유', unit: '' },
    ],
    workOrderCount: 20,
  },
  {
    id: 6,
    name: 'C동 급수펌프 #1',
    code: 'SANIT-C-006',
    type: '급수펌프',
    buildingName: 'C동',
    floor: '지하 1층',
    location: '펌프실',
    manufacturer: '한국펌프',
    model: 'WP-1000',
    capacity: '1000LPM',
    installDate: '2021-02-15',
    lastCheckDate: '2024-02-08',
    status: 'NORMAL',
    managerName: '박민수',
    managerPhone: '010-3456-7890',
    description: 'C동 생활 급수 펌프입니다.',
    firstCategoryId: 4,
    firstClassName: '위생설비',
    secondCategoryId: 41,
    secondClassName: '급수설비',
    imageUrl: 'https://picsum.photos/400/300?random=6',
    specifications: [
      { name: '양정', value: '80', unit: 'm' },
      { name: '유량', value: '1000', unit: 'LPM' },
      { name: '전동기 출력', value: '30', unit: 'kW' },
    ],
    workOrderCount: 6,
  },
  {
    id: 7,
    name: 'A동 EHP #5',
    code: 'HVAC-A-007',
    type: '냉난방기',
    buildingName: 'A동',
    floor: '3층',
    location: '사무실',
    manufacturer: 'LG전자',
    model: 'EHP-15',
    capacity: '15HP',
    installDate: '2022-06-01',
    lastCheckDate: '2024-02-03',
    status: 'NORMAL',
    managerName: '김철수',
    managerPhone: '010-1234-5678',
    firstCategoryId: 1,
    firstClassName: '공조설비',
    secondCategoryId: 11,
    secondClassName: '냉난방기',
    thirdCategoryId: 111,
    thirdClassName: '에어컨',
    imageUrl: 'https://picsum.photos/400/300?random=7',
    specifications: [
      { name: '냉방 용량', value: '15', unit: 'HP' },
      { name: '난방 용량', value: '17', unit: 'HP' },
      { name: '전압', value: '380', unit: 'V' },
    ],
    workOrderCount: 3,
  },
  {
    id: 8,
    name: 'B동 수변전설비',
    code: 'ELEC-B-008',
    type: '배전반',
    buildingName: 'B동',
    floor: '지하 2층',
    location: '전기실',
    manufacturer: 'LS산전',
    model: 'PDB-2000',
    installDate: '2019-11-20',
    lastCheckDate: '2024-01-25',
    status: 'NORMAL',
    managerName: '이영희',
    managerPhone: '010-2345-6789',
    firstCategoryId: 2,
    firstClassName: '전기설비',
    secondCategoryId: 22,
    secondClassName: '배전반',
    imageUrl: 'https://picsum.photos/400/300?random=8',
    specifications: [
      { name: '정격 전류', value: '2000', unit: 'A' },
      { name: '전압', value: '380', unit: 'V' },
    ],
    workOrderCount: 10,
  },
];
