/**
 * 고객불편(VOC/Claim) Mock 데이터
 */
import type { ClaimDTO } from '../types';

export const mockClaims: ClaimDTO[] = [
  {
    id: 1,
    title: '회의실 온도가 너무 높아요',
    content: '5층 대회의실 에어컨이 제대로 작동하지 않아 온도가 너무 높습니다. 빠른 조치 부탁드립니다.',
    state: 'PROCESSING',
    stateName: '처리중',
    receivedDate: '2026-02-10 09:30',
    buildingName: 'A동',
    floor: '5층',
    zone: '동측',
    location: '대회의실',
    phoneNumber: '010-1234-5678',
    receiverName: '홍길동',
    processorName: '김담당',
    isTemplate: true,
    templateType: 'HOT',
    attachments: [
      {
        id: 1,
        fileName: 'temperature.jpg',
        fileUrl: 'https://example.com/temperature.jpg',
        fileType: 'image/jpeg',
      },
    ],
  },
  {
    id: 2,
    title: '화장실 청소 요청',
    content: '3층 남자 화장실 청소가 필요합니다.',
    state: 'COMPLETED',
    stateName: '완료',
    receivedDate: '2026-02-09 14:20',
    processedDate: '2026-02-09 15:00',
    completedDate: '2026-02-09 15:30',
    buildingName: 'B동',
    floor: '3층',
    zone: '서측',
    location: '남자화장실',
    phoneNumber: '010-9876-5432',
    receiverName: '이철수',
    processorName: '박청소',
    isTemplate: true,
    templateType: 'CLEANING',
    processResult: '청소 완료하였습니다.',
  },
  {
    id: 3,
    title: '사무실이 추워요',
    content: '7층 사무실 난방이 약해서 너무 춥습니다. 온도 조절 부탁드립니다.',
    state: 'RECEIVED',
    stateName: '접수',
    receivedDate: '2026-02-10 10:15',
    buildingName: 'A동',
    floor: '7층',
    zone: '북측',
    location: '사무실',
    phoneNumber: '010-5555-6666',
    receiverName: '최현우',
    isTemplate: true,
    templateType: 'COLD',
  },
  {
    id: 4,
    title: '엘리베이터 버튼 고장',
    content: '2층 엘리베이터 올라가는 버튼이 작동하지 않습니다.',
    state: 'PROCESSING',
    stateName: '처리중',
    receivedDate: '2026-02-10 08:45',
    processedDate: '2026-02-10 09:00',
    buildingName: 'C동',
    floor: '2층',
    zone: '중앙',
    location: '엘리베이터홀',
    phoneNumber: '010-7777-8888',
    receiverName: '정민수',
    processorName: '강기술',
    isTemplate: true,
    templateType: 'ELEVATOR',
    attachments: [
      {
        id: 2,
        fileName: 'elevator_button.jpg',
        fileUrl: 'https://example.com/elevator.jpg',
        fileType: 'image/jpeg',
      },
    ],
  },
  {
    id: 5,
    title: '주차장 조명 꺼짐',
    content: '지하 1층 주차장 A구역 조명이 여러 개 꺼져 있어 어둡습니다.',
    state: 'COMPLETED',
    stateName: '완료',
    receivedDate: '2026-02-08 16:30',
    processedDate: '2026-02-08 17:00',
    completedDate: '2026-02-08 18:00',
    buildingName: '지하주차장',
    floor: 'B1',
    zone: 'A구역',
    location: '주차장',
    phoneNumber: '010-3333-4444',
    receiverName: '송주차',
    processorName: '유전기',
    isTemplate: true,
    templateType: 'LIGHT',
    processResult: '조명 교체 완료하였습니다.',
  },
  {
    id: 6,
    title: '화장실 누수',
    content: '4층 여자 화장실 세면대에서 물이 계속 새고 있습니다.',
    state: 'PROCESSING',
    stateName: '처리중',
    receivedDate: '2026-02-10 11:00',
    processedDate: '2026-02-10 11:15',
    buildingName: 'A동',
    floor: '4층',
    zone: '동측',
    location: '여자화장실',
    phoneNumber: '010-2222-3333',
    receiverName: '김미영',
    processorName: '이설비',
    isTemplate: true,
    templateType: 'WATER',
    attachments: [
      {
        id: 3,
        fileName: 'water_leak.jpg',
        fileUrl: 'https://example.com/leak.jpg',
        fileType: 'image/jpeg',
      },
      {
        id: 4,
        fileName: 'water_leak2.jpg',
        fileUrl: 'https://example.com/leak2.jpg',
        fileType: 'image/jpeg',
      },
    ],
  },
  {
    id: 7,
    title: '복도 소음',
    content: '6층 복도에서 계속 소음이 발생합니다. 확인 부탁드립니다.',
    state: 'RECEIVED',
    stateName: '접수',
    receivedDate: '2026-02-10 12:00',
    buildingName: 'B동',
    floor: '6층',
    zone: '남측',
    location: '복도',
    phoneNumber: '010-8888-9999',
    receiverName: '박소음',
    isTemplate: true,
    templateType: 'NOISE',
  },
  {
    id: 8,
    title: '주차 단속 요청',
    content: '무단 주차 차량이 있어 주차가 어렵습니다. 단속 부탁드립니다.',
    state: 'COMPLETED',
    stateName: '완료',
    receivedDate: '2026-02-09 09:00',
    processedDate: '2026-02-09 09:30',
    completedDate: '2026-02-09 10:30',
    buildingName: '지하주차장',
    floor: 'B2',
    zone: 'B구역',
    location: '주차장',
    phoneNumber: '010-6666-7777',
    receiverName: '최운전',
    processorName: '안보안',
    isTemplate: true,
    templateType: 'PARKING',
    processResult: '무단 주차 차량 견인 조치 완료하였습니다.',
  },
];
